courses/urls.py
from django.urls import path
from . import views

app_name = 'courses'
urlpatterns = [
    path('list/', views.CourseList.as_view(), name='course-list'),
    path('<int:pk>/', views.CourseDetails.as_view(), name='course-details'),
]

seedofknowledge/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', auth_views.login, {'template_name': 'core/login.html' }, name='login'),
    path('logout/', auth_views.logout, name='logout'),
    path('dashboard/', views.dashboard, name='dashboard'),

    path('subjects/', include('subjects.urls', namespace='subjects')),
    path('courses/', include('courses.urls', namespace='courses')),
]

subjects/urls.py
from django.urls import path
from . import views

app_name = 'subjects'
urlpatterns = [
    path('list', views.SubjectList.as_view(), name='subject-list'),
    path('<int:pk>', views.SubjectDetail.as_view(), name='subject-detail'),
]

core/models.py
from django.db import models

# Create your models here.

courses/models.py
from django.db import models
from django.urls import reverse 
from subjects.models import Subject, Unit
from datetime import datetime

class Course(models.Model):
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject.name

    def save(self, *args, **kwargs):
        new = self.pk is None
        super().save(*args, **kwargs)
        if new:
            subject = self.subject
            units = Unit.objects.filter(subject=subject)
            for unit in units:
                lecture = Lecture(course=self, unit=unit.name, 
                        date=datetime.today(), start_time=datetime.now(), 
                        end_time=datetime.now())
                lecture.save()

class Lecture(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    unit = models.CharField(max_length=100)
    date = models.DateField()
    start_time = models.TimeField()
    end_time = models.TimeField()

    def __str__(self):
        return "{} on {} ({} - {})".format(self.course, self.date, 
                self.start_time, self.end_time)

subjects/models.py
from django.db import models

class Subject(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()

    def __str__(self):
        return self.name
    
class Unit(models.Model):
    number = models.IntegerField()
    name = models.CharField(max_length=255)
    description = models.TextField()
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("number", "subject")
        ordering = ["subject", "number"]

core/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from django.contrib.auth.forms import UserCreationForm

# Create your views here.

def index(request):
    return render(request, 'core/landing.html', {})

def register(request):
    pass

class RegisterView(FormView):
    template_name = 'core/signup.html'
    form_class = UserCreationForm
    success_url = '/'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

def dashboard(request):
    return render(request, 'core/dashboard.html', {})

courses/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Course

class CourseList(ListView):
    model = Course

class CourseDetails(DetailView):
    model = Course

landing/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'landing/index.html', {})

subjects/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import Subject

class SubjectList(ListView):
    model = Subject

class SubjectDetail(DetailView):
    model = Subject

core/templates/base.html
<!doctype html>

{% load bootstrap4 %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}Seed of Knowledge {% endblock %}</title>
        {% bootstrap_css %}
        {% bootstrap_javascript %}
    </head>

    <body>
        {% block navbar %}{% endblock %}
        {% block content %}{% endblock %}
    </body>
</html>

core/templates/base_authenticated.html
{% extends "base.html" %}

{% block navbar %}
<nav class="navbar navbar-dark bg-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'subjects:subject-list' %}">Courses</a>
        </li>
    </ul>
</nav>
{% endblock %}

core/templates/core/dashboard.html
{% extends "base_authenticated.html" %}

{% block content %}
<h1>Dashboard</h1>

<p>Welcome, {{ user }}. <a href="{% url 'logout' %}">Log out</a></p>
{% endblock %}

core/templates/core/landing.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome!</h1>

{% if user.is_authenticated %}
    <p><a href="{% url 'logout' %}">Logout</a></p>
{% else %}
    <p><a href="{% url 'register' %}">Register</a></p>
    <p><a href="{% url 'login' %}">Login</a></p>
{% endif %}
{% endblock %}

core/templates/core/login.html
{% extends "base.html" %}

{% block content %}
<h2>Login</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log in</button>
</form>
{% endblock %}

core/templates/core/signup.html
{% extends "base.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
</form>
{% endblock %}

courses/templates/courses/course_detail.html
{% extends "base_authenticated.html" %}

{% block content %}
<p>{{ object.name }}</p>
<p>{{ object.description }}</p>
{% endblock %}

courses/templates/courses/course_list.html
{% extends "base.html" %}

{% block content %}
<h2>Courses</h2>

<ul>
    {% for course in object_list %}
    <li><a href="{% url 'courses:course-details' course.id %}">{{ course }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

landing/templates/landing/index.html
{% extends "base.html" %}

{% block content %}
<h1>Welcome!</h1>
{% endblock %}

subjects/templates/subjects/subject_detail.html
{% extends "base_authenticated.html" %}

{% block content %}
<p>{{ object.name }}</p>
<p>{{ object.description }}</p>
{% endblock %}

subjects/templates/subjects/subject_list.html
{% extends "base_authenticated.html" %}

{% block content %}
<h2>Course List</h2>

<ul>
    {% for subject in object_list %}
    <li><a href="{% url 'subjects:subject-detail' subject.id %}">{{ subject }}</a></li>
    {% endfor %}
</ul>
{% endblock %}